# History improvements 
export HISTFILE=~/.zsh_history
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
export SAVEHIST=100000
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
# Vimode
bindkey -v
bindkey -M vicmd "?" history-incremental-search-backward
bindkey -M vicmd "/" history-incremental-search-forward

# Aliases
alias gicm="git checkout main && git pull || git checkout master && git pull"
alias gic="git checkout"

alias difft="difftastic"
alias vim="nvim"

# PATH
export PATH=$PATH:$HOME/.bin:$HOME/go/bin

# ENV
export EDITOR=vim

# Starship
export STARSHIP_CONFIG=~/.starship.toml
eval "$(starship init zsh)"
